-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
CREATE TABLE IF NOT EXISTS public.cliente
(
    cpf character varying(100) NOT NULL,
    nome character varying(100) NOT NULL,
    endereco text,
    fone bigint,
    PRIMARY KEY (cpf),
	CONSTRAINT check_person CHECK(fone>0)
);

CREATE TABLE IF NOT EXISTS public.aviao
(
    naviao integer NOT NULL,
    fabricante character varying(100) NOT NULL,
    capacidade integer NOT NULL,
    tipo character varying(100) NOT NULL,
    PRIMARY KEY (naviao),
	CONSTRAINT check_plane CHECK(capacidade>0)
);

CREATE TABLE IF NOT EXISTS public.aeroporto
(
    codaeropor character varying(100) NOT NULL,
    nome character varying(100) NOT NULL,
    localizacao text NOT NULL,
    PRIMARY KEY (codaeropor)
);

CREATE TABLE IF NOT EXISTS public.voo
(
    nvoo character varying(100) NOT NULL,
    companhia character varying(100) NOT NULL,
    horario date NOT NULL,
    fk_naviao integer NOT NULL,
    fk_codaeropor character varying(100) NOT NULL,
    PRIMARY KEY (nvoo)
);

CREATE TABLE IF NOT EXISTS public.passagem
(
    npassagem bigint NOT NULL UNIQUE,
    classe character varying(20) NOT NULL,
    npoltrona integer NOT NULL,
    preco double precision,
    fk_cpf character varying(100) NOT NULL,
    fk_nvoo character varying(100) NOT NULL,
    PRIMARY KEY (npoltrona, fk_nvoo),
	CONSTRAINT check_passage CHECK(npoltrona>0 AND preco>=0 AND
								   npassagem>0)
);

ALTER TABLE public.voo
    ADD FOREIGN KEY (fk_naviao)
    REFERENCES public.aviao (naviao)
    NOT VALID;


ALTER TABLE public.voo
    ADD FOREIGN KEY (fk_codaeropor)
    REFERENCES public.aeroporto (codaeropor)
    NOT VALID;


ALTER TABLE public.passagem
    ADD FOREIGN KEY (fk_cpf)
    REFERENCES public.cliente (cpf)
    NOT VALID;


ALTER TABLE public.passagem
    ADD FOREIGN KEY (fk_nvoo)
    REFERENCES public.voo (nvoo)
    NOT VALID;